### ISSUE TITLE
Crash with Chartboost.

### ISSUE THREAD

**Issue by sourav-paul** [mopub/mopub-unity-sdk#102]
Crashes only in presence of Chartboost adapter and it's dependencies.

I've tried with 7 other adopter of different networks. Works fine. But when Chartboost adapter is imported, build crashes with attached error.

Crash happens with just Mopub and Chartboost adapter only.

#### Steps to reproduce the behavior:
Import Mopub 5.10.0, auto resolve, import Chartboost from Mopub SDK import window, auto resolve, load demo scene provided, in mopubmanager prefab add Chartboost as network, build android,  run

#### Expected behavior:
Demo GUI should be seen and wait for input

#### Evidence: check screenshots.
![Screenshot_2020-01-28-18-46-55-342_com miui bugreport](https://user-images.githubusercontent.com/6245802/73266402-097fea80-4201-11ea-99db-702367a971fe.jpg)
![Screenshot_2020-01-28-18-47-03-466_com miui bugreport](https://user-images.githubusercontent.com/6245802/73266411-0dac0800-4201-11ea-880b-901dd4d0f2ec.jpg)

**Comment by hmertkahraman** [comment]
Hi @sourav-paul ,

Looking at the errors you provided, it appears that Chartboost classes are missing, meaning that although _Chartboost-MoPub Adapters_ are present, but the _Chartboost SDK_ isn't present.

This is since, unlike our other network SDK installations, Chartboost SDK requires manual installation for Unity. This is an exception for Chartboost (as they're SDK is not currently on BinTray at this time, and require a manual installation).

We provide this warning on the MoPub SDK Plugin for Unity. It can be found by the `?` icon on the SDK Manager, like below:

![Screenshot 2020-01-29 at 10 39 09](https://user-images.githubusercontent.com/47573140/73349777-b7cc7400-4283-11ea-9d21-c6e5678d3cae.png)

Once you click this warning button, it will take you to this link where it explains how to install Chartboost SDK manually:
https://developers.mopub.com/publishers/mediation/networks/chartboost/

After following the steps to install Chartboost SDK manually and retrying again, please let us know if you still have the problem.

Thanks,
MoPub Team
