### ISSUE TITLE
Android: reopen application

### ISSUE THREAD

**Issue by dworkinnn** [mopub/mopub-unity-sdk#109]
The application restarts when clicking on a banner, when opening an inter or video. (only on Google Pixel 3a and LG G5)

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:

1. Download last mopub unity sdk
2. Build to device scene "MoPubDemoScene"
3. Open app on device and send request interstitial
4. App reopen or restart (inter dont shown)

**Comment by dworkinnn** [comment]
I disable "developer mode" on devices and error has disappeared.

**Comment by chauduyphanvu** [comment]
@dworkinnn, thanks for letting us know! First, check to see if you have previously enabled the "Don't keep Activities" [setting](https://stackoverflow.com/questions/22400859/dont-keep-activities-what-is-it-for). We use Activities for interstitial ads, so if the developer options are enabled and "Don't keep Activities" is checked, then that would explain why interstitial ads can't show, because Android has discarded the Activities when you leave the app.

Let us know if there are any questions.

Vu Chau
MoPub Team

**Comment by dworkinnn** [comment]
@chauduyphanvu, yes, this feature has been enabled. After shutdown, everything works correctly. Thanks.
