### ISSUE TITLE
Wrong consent status

### ISSUE THREAD

**Issue by nazgull30** [mopub/mopub-unity-sdk#116]
After I accept the terms in the Mopub consent popup, in the event EmitConsentStatusChangedEvent I received status Denied not Confirmed.
Also OnConsentDialogDismissedEvent is not fired.

#### MoPub SDK Version:
5.12.1
#### Unity Version:
2018.4.15

#### Steps to reproduce the behavior:
1. Launch an app first time.
2. Accept mopub consent.
3. Close consent.

#### Expected behavior:
1. EmitConsentStatusChangedEvent should be fired with Confirmed status.
2. OnConsentDialogDismissedEvent should be fired.

#### Observed behavior:
1. EmitConsentStatusChangedEvent is fired with Denied status.
2. OnConsentDialogDismissedEvent is not fired.

#### Evidence:
Video: https://drive.google.com/open?id=1Ur9uHVu3fPav4TJcS-7BcXdzZgdZhzsy
Log: https://pastebin.com/zPL8jf1x

**Comment by aornelas** [comment]
Thanks for reporting! We are investigating this issue.

**Comment by aornelas** [comment]
Turns out there's a bug in the *logging* of that event (the old and new consent status are flipped):
<img width="816" alt="Screen_Shot_2020-04-29_at_11_51_23_AM" src="https://user-images.githubusercontent.com/286010/80634919-0834a880-8a10-11ea-8c64-19c8405200a6.png">

The actual consent status returned by the callback is correct (as you can see in the sample app UI). The logging bug will be fixed in the next release, thanks for letting us know!

Still investigating the `OnConsentDialogDismissedEvent` missing...

**Comment by nazgull30** [comment]
yes, actual status is correct. 
Ok, I will be looking forward till the next releases.

**Comment by aornelas** [comment]
Ok, I've tracked down the issue with `OnConsentDialogDismissedEvent`. This will be fixed on the next release as well!

**Comment by chauduyphanvu** [comment]
Fixed in the 5.13.0 release (https://github.com/mopub/mopub-unity-sdk/commit/efc1845af25722d6bf0aa79cd963bce48ee8c8ba).
