### ISSUE TITLE
5.13 podspec point to 5.12.1 version

### ISSUE THREAD

**Issue by paradizIscool** [mopub/mopub-unity-sdk#126]
Hi,

I start to update from 5.10 to 5.13 and I notice that the podspec from the sample app is pointing to 5.12.1 ios sdk version. I guess this should not be the case.

Best regards 
Lionel

**Comment by chauduyphanvu** [comment]
@paradizIscool, thanks for letting us know! While [that version](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Plugins/iOS/MoPub-SDK-Plugin.podspec#L3) should also be 5.13.0, it's only our Unity iOS wrapper version. This does't affect your integration, because the [actual iOS SDK](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Scripts/Editor/MoPubDependencies.xml#L14) that exists in your project will be 5.13.0. As a result, you will still get the up-to-date 5.13.0 iOS SDK correctly.

We'll bump the Unity iOS wrapper version, but let us know if you see any issues in the meantime!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This is now fixed in v5.13.1: https://github.com/mopub/mopub-unity-sdk/commit/a37426459377c18d46bccb8fa4c8cc2bea9c267e#diff-d11543ce61d02e0e0ae988ef5858cbfd.
