### ISSUE TITLE
Can't find a way to change banner position

### ISSUE THREAD

**Issue by shlighter** [mopub/mopub-unity-sdk#128]
One line summary of the issue here - Trying to place a banner in  a list view (every 5 items a banner)

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

Unity version: 2019.4.1.f1
Mopub SDK version: 5.13.0

#### Steps to reproduce the behavior:
On admob I was able to place a medium rectangle banner inside a recycler view 
but now after switching to mopub I can't seem to find a way to change the banner position or parent gameobject
Is it not supported for mopub Unity to place banners in a list? What's the way to do it then?

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by hmertkahraman** [comment]
Hi @shlighter ,

From the description we understand that you'd like to place a banner inside a recycler view on Unity > Android project. Will what you're trying to accomplish be something like our [Native ads](https://developers.mopub.com/publishers/android/native-recyclerview/)? Please see [here](https://developers.mopub.com/publishers/best-practices/native-ads/) for additional reference, and [here](https://developers.mopub.com/publishers/best-practices/native-integration-overview/) for layout examples on our Native ads. 
If this is what you're trying to achieve, again, on Android platform, we consider these as a Native ad, rather than a banner ad.
Our Unity plugin currently does not support Native ads and is experimental.

If you're referring to standard Banner ads, on Unity, you cannot place them inside recycler views. For these banners you can place them with the `AdPosition` property of the banner that's being requested on `RequestBanner` method.

Please let us know which ad you'd like to utilize.

Thanks,
Mert
