### ISSUE TITLE
MoPub 5.15.0 Unity SDK OnRewardedVideoExpiredEvent is not fired

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#157]
Using the MoPub Unity Demo, OnRewardedVideoExpiredEvent is not fired after waiting for 4 hours.
Is Expired Event depends of the VideoAd Mediation Network ?
We currently integrate the AppLovin, Facebook, ironSource, UnityAds, Vungle, HyprMX

#### Ad Unit IDs used in reproducing the issue: 
364e003259fa4311bb3b8de5f0f4a456 (Android)
1740ece3aa07447eae64b986ce80e2c4 (iOS)

#### Steps to reproduce the behavior:
1. Load the VideoAd
2. VideoAd is Loaded
2. Wait for more than 4 hours

#### Expected behavior:
OnRewardedVideoExpiredEvent is fired

#### Observed behavior:
OnRewardedVideoExpiredEvent is not fired

**Comment by hmertkahraman** [comment]
Hi @psstevenchan ,

Thanks for reaching out to us and providing details. 

Only a few of our certified networks do have expiration logic on RV's: AdColony, Facebook, Snap, Verizon. Also our Marketplace ads have it as well. For other networks you shouldn't be expecting expiration logic to propagate on our adapters although this can change in the future.

For Custom networks such as HyprMX, please ensure the network SDK is calling expiration properly and the custom adapters to map it to the expiration event on Unity.

Are you testing this on Unity>Android only?

For Android, we don't have an expiration callback so OnRewardedVideoExpiredEvent wouldn't propogate to a "expire" event, instead for each network it will behave differently according to their adapters. You may check respective adapters to see what happens.

If this issue is happening on iOS as well please let us know.

Thanks,
MoPub Team

**Comment by psstevenchan** [comment]
1. Only Unity iOS RewardedVideo Ad Marketplace, AdColony, Facebook Snap Verizon has expire callback ?
2. All Unity Android RewardedVideo Ad don't have expire callback ?
3. Is Marketplace and other networks Ad will expire after loaded ? must be 4 hours ?
4. If Ad loaded and then expired without callback, is it possible to know it is expired or not without play Ad to return expired error ?
5. If Ad loaded and then expired without callback, MoPub.HasRewardedVideo(adUnitId) is true or false ?

**Comment by hmertkahraman** [comment]
Hi @psstevenchan ,
For 1 and 2 - Not entirely true to say there are expiration callbacks because: 

**Important takeaway is that ad expiration logic is not widely available and is not treated in a standard way.** 

We strongly recommend you to check network adapters on iOS and see how they're handled individually. Our network adapters will try to handle the expiration in different ways mostly be leading to failures on show or raising a failure. The fact that a network expires ads, doesn't mean MoPub will handle it for that network. 

3- For marketplace expiration is 4 hours and our sdk will call the ad did expire callback.
4- Unfortunately no, if the ad source doesn't expose us if the ad is expired, we cannot map that logic.
5- This is expected to return false on MPX and might differ for each network adapter.

Thanks!

**Comment by hmertkahraman** [comment]
Hi @psstevenchan ,

Following up on #4, can we ask if your ad sources provide error codes or APIs available to check expiry status (for the ads you're concerned with)?

Thanks,
Mert
