### ISSUE TITLE
apps are crashing after updation to latest sdk with gdpr concent

### ISSUE THREAD

**Issue by yawarabbasshah** [mopub/mopub-unity-sdk#17]
at com.mopub.common.privacy.AdvertisingId.equals (AdvertisingId.java:137)
  at com.mopub.common.privacy.MoPubIdentifier.setAdvertisingInfo (MoPubIdentifier.java:187)
  at com.mopub.common.privacy.MoPubIdentifier.setAdvertisingInfo (MoPubIdentifier.java:179)
  at com.mopub.common.privacy.MoPubIdentifier.refreshAdvertisingInfoBackgroundThread (MoPubIdentifier.java:98)
  at com.mopub.common.privacy.MoPubIdentifier$RefreshAdvertisingInfoAsyncTask.doInBackground (MoPubIdentifier.java:255)
  at com.mopub.common.privacy.MoPubIdentifier$RefreshAdvertisingInfoAsyncTask.doInBackground (MoPubIdentifier.java:251)
  at android.os.AsyncTask$2.call (AsyncTask.java:305)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)

android.os.AsyncTask$3.done (AsyncTask.java:325)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:223)
  at java.util.concurrent.FutureTask.run (FutureTask.java:242)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:243)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

**Comment by aornelas** [comment]
Hi there, sorry you're having problems with our latest release.

Could you please provide more details? Some that would help us investigate:
* what are you trying to do when it crashes?
* what is the actual error? (above seems to only include the stack trace, but not the error)
* is this a consistent crash or only happens sometimes?

Thanks!

**Comment by aornelas** [comment]
... oh, and also please let us know which version of Unity and which device/OS this happens on. Thanks!

**Comment by yawarabbasshah** [comment]
i am using unity 5.6.2

**Comment by yawarabbasshah** [comment]
this is happening on android 6.0 ,7.0,5.1,7.1 this error is showed by google play console. I had tested it on my device but it didnot crashed

**Comment by aornelas** [comment]
ok, that version is supported, so the issue must be elsewhere...

Once you provide the other details, we can investigate further.

**Comment by yawarabbasshah** [comment]
i am trying to show concent dialogue and try requesting ads in splash screen so it my happen because of it

**Comment by yawarabbasshah** [comment]
there is nothing more I can tell because nothing else is shown on google play console what my cause it?

**Comment by aornelas** [comment]
Thanks for the additional details.

A few things to check:
* make sure the sdk is initialized before you try to show consent dialog or load ads
* check whether you should show the dialog before attempting by using the `ShouldShowConsentDialog` API (or similar)
* related to the previous point, are you in a GDPR-applicable area when you are testing? what about your users who get the crash?

**Comment by yawarabbasshah** [comment]
location is not shown for crashes

**Comment by aornelas** [comment]
Ah ok, that's very useful... I wonder if those users have Do Not Track enabled which yields a null advertising ID? perhaps you could reproduce the issue that way...

I'll confer with my Android colleagues in the morning and let you know if we have other hypotheses!

**Comment by yawarabbasshah** [comment]
ok thanks i will wait for it.

**Comment by uchitel** [comment]
The exception means something is wrong with Google Play Services. The SDK does read correctly AdvertisingIdClient.Info object from the device, but the advertisingId is null for some reason. 
- First of all check the Google Play Services library is included into the project the same way how it is done in the MoPub sample app. 
- Second, is there a chance the device was not updated for a while? We had Google Play Services behaving weirdly on the device that did not see update for a couple years.

**Comment by yawarabbasshah** [comment]
which google play services library i should use. with which name is it present in sample app.

**Comment by aornelas** [comment]
Please have a look at the relevant readme:
https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/Plugins/Android/README.txt

**Comment by uchitel** [comment]
Android sample gradle file https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/build.gradle

**Comment by yawarabbasshah** [comment]
i had placed these files already here. The Issue is with some of the devices i don't know where the crash is appearing crash rate is 1.22% and google play console show the reason that i had pasted here in the tread.

**Comment by yawarabbasshah** [comment]
![supportss](https://user-images.githubusercontent.com/39720090/40825226-6b381328-6590-11e8-8e05-08e5ccf897e5.PNG)

these are the files that i added in plugin androids folder

**Comment by chauduyphanvu1** [comment]
You might want to try removing the "ads-lite" one. It's a subset of the larger "ads" one anyway, so you won't need it. Also, the "lite" one doesn't have the class the reads the advertising ID from your device, which might make the advertising ID null. Better leave it to the "ads" artifact to do that job.

**Comment by aornelas** [comment]
The [5.1.0 release](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.1.0) includes the fix mentioned above.

Thanks again for reporting!

**Comment by yawarabbasshah** [comment]
Thank you all I am going to try it.

**Comment by Cascade-Habib** [comment]
I upgraded to V 5.1 but not able to see consent dialogue.
i have proxy installed, i switched it to Italy. I verified my ip address using https://www.whatismyip.com/
and confirmed that my device location was from ITALY.
when i installed the application for the VERY FIRST TIME, i debugged the application and found following results
isSDKInitialized= True
isGDPRApplicable= NULL
ShouldShowConsentDialog = false;

And I WAS NOT ABLE TO SEE THE CONSENT DIALOGUE.

i closed the application and RE-LAUNCHED the application second time and below were the stats
isSDKInitialized= False [it never initializes except the very first time of install of the application]
isGDPRApplicable= True
ShouldShowConsentDialog = True;

and this time too , i was not able to see the consent dialogue

I am using unity 5.5.1

Could you please suggest the solution so that i can present consent dialogue using unity.

**Comment by aornelas** [comment]
Hi @Cascade-Habib,

The first `isGDPRApplicable=NULL` is likely due to a GDPR-synch not happening yet, so it shouldn't be an issue (even if you don't restart, a synch would happen at most in 5 minutes). Once `isGDPRApplicable` and `ShouldShowConsentDialog` are both `True`, you should be able to request and show a consent dialog using the relevant API methods: [`LoadConsentDialog`](https://github.com/mopub/mopub-unity-sdk/blob/747f67c396f742518a2d6eeb0b3046dcfa711e8b/unity-sample-app/Assets/MoPub/Internal/MoPubUnityEditor.cs#L581) and [`ShowConsentDialog`](https://github.com/mopub/mopub-unity-sdk/blob/747f67c396f742518a2d6eeb0b3046dcfa711e8b/unity-sample-app/Assets/MoPub/Internal/MoPubUnityEditor.cs#L610).

**If you're still having trouble, please open a separate issue and include any errors you are seeing so we can better assist you.**

Thanks!

**Comment by Cascade-Habib** [comment]
1. what do you mean by GDPR sysnch not happening yet, if it happens in 5 minutes, who should we show the consent dialogue, we are using mopub ads in our games, and average game play time is 1 or 2 minutes and life time play is ONE TIME in most cases, that means we can not show mopub consent dialogue becuase of this synch.
2. when we install the game and play it very first time, ShouldShowConsentDialog = true but isGDPRApplicable = NULL, that means consent dialogue can not be shown.

3. when we close the game, and restart it 2nd time[subsequent time], then both 
ShouldShowConsentDialog = True
isGDPRApplicable  = True
But isSDKInitialized = false [WHY is it false, and why consent dialogue does not show as you mentioned in your previous message if isGDPRApplicable  and ShouldShowConsentDialog are both true then consent dialogue should show up but it never shows up[perhaps this time  isSDKInitialized = false]

please see and suggest us solution, we are using mopub and blocked because of your new upgrades.

**Comment by aornelas** [comment]
@Cascade-Habib seems you may not be initializing the SDK per [the documentation](https://developers.mopub.com/docs/unity/initialization/). Please give that a try and **email support@mopub.com if you're still having issues** so our support team can help you through it, as I will no longer follow up in this thread.

Thanks,
Andrés
