### ISSUE TITLE
Error ITMS-90432

### ISSUE THREAD

**Issue by wixar172** [mopub/mopub-unity-sdk#173]
App fails to validate after submitting to the app store with error ITMS-90432 

-  I visited https://developers.mopub.com/ and found no answer
-  I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
-  I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior:
1-add mopub to your project, configure it, export the app to xcode (v14.4 GM)
2- build the app on a device and it runs normally
3-archive the app, and  send it to the app store
4-after upload completes, the validation process starts and then fails with the error: 

ITMS-90432 invalid swift support, the file Gamename.app/Frameworks/MoPubBinding.m, Gamename.app/Frameworks/MoPubManager.mm, 
Gamename.app/Frameworks/MopubManager.h, Gamename.app/Frameworks/SwiftCompatibility.swift doesn't have the correct file type for the location. Ensure you're using the correct file. Rebuild your app using the current public (GM) version of xcode and resubmit it"

**Comment by xxGAGASxx** [comment]
Same issue. I have been suffering with this issue for 3 days, still no success ((

**Comment by mrkaratechamp** [comment]
same error here, how the hell you upload a build without testing it???

**Comment by BlueSpiritbox** [comment]
Same issue here. Building it to a device and archiving works fine, but the error shows up once I try to upload it to the app store

**Comment by chauduyphanvu** [comment]
Hi all, which Xcode version are you using? According to the error message ("Ensure you're using the correct file. Rebuild your app using the current public (GM) version of xcode and resubmit it"), it appears you might have used a beta version of Xcode, which we do not support.

Vu Chau
MoPub Team

**Comment by mrkaratechamp** [comment]
Hi @chauduyphanvu , I'm using Xcode 12.4 (12D4e), as far I know this is the latest stable release (as you also said), so I think it's not the xcode version the problem. also in my case I use cocoapods to install all skds after compile with unity and generate the xcode project, the cocoapods generate a xworkspace file to open the project, and everythings works great when we run the project into our devices, (iphone and ipad), also when archive and export, works too, this issue is only when trying to upload to itunes connect. This process using cocoapods is like we always do in the past, we are using mopub sdk from version 5.8.0, always updating frequently, (5.10, 5.12, 5.13 ... etc) and only got this error with this new 5.16.3 (already try downgrade to 5.16.0, but same error).

please let me know if you need any extra info that helps to speed up this issue.

thanks!

**Comment by chauduyphanvu** [comment]
@mrkaratechamp, thank you for the information. I've relayed it to the rest of the team and we are looking into this further. Stay tuned for an update!

**Comment by chauduyphanvu** [comment]
Hi all, we have a resolution for this that will be included in the upcoming MoPub Unity SDK release. In the meantime, you can remove the files from the `Build Phases` > `Embedded Frameworks` list in the Xcode project, or uncheck the `Add to Embedded Binaries` option in all four of those files in the Unity project.

The four files that need to have `Add to Embedded Binaries` unchecked are ones under `MoPub/Plugins/iOS`. They need to be unchecked one-by-one. Click `Apply` each time.

Let us know if that resolves the issue!

**Comment by mrkaratechamp** [comment]
@chauduyphanvu  thanks!, that's solve the problem, was difficult to think mopub sdk didn't need that files to be embed, because  it's comes in that way. but that makes no playlable issue and can publish to itunes connect! really many thanks!

**Comment by chauduyphanvu** [comment]
This issue has been resolved in [v5.16.4](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.16.4) of the MoPub Unity SDK. Please update to the new release and let us know if the issue persists. Thank you!
