### ISSUE TITLE
banner iOS mopub 5.16.4

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#182]
After update mopub to 5.16.4 I get this error on my iPhone

```csharp
MoPub.RequestBanner(bannerAdUnit, MoPub.AdPosition.BottomCenter, MoPub.MaxAdSize.ScreenWidthHeight50, GetKeyWords(), GetUserDataKeyWords());
```
```
[Warning] AdsManager OnAdFailedEvent() - adUnitId=746dc262fdbd4676a8da423917672f79, error=Cannot determine a size for flexible width because the frame width is not set.
	Bonobroo.Ads.AdsManager:OnAdFailedEvent(String, String)
```

Device iPhone 6 Plus (iOS 12.5.1)
Unity 2020.3.0f1

**Comment by chauduyphanvu** [comment]
@agrobost, that's not expected at all. Did you call `LoadBannerPluginsForAdUnits(string[] adUnitIds)`? The error message means the frame for your banner ad has not been set in iOS, but that shouldn't be a requirement since you are building from Unity.

Could you confirm if you also see the same behavior from our [Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) using the same ad unit ID and request logic?

Vu Chau
MoPub Team

**Comment by agrobost** [comment]
Yes I call  ```LoadBannerPluginsForAdUnits(string[] adUnitIds)``` and I follow the same logic that the sample app.

If I revert the modifications in MoPubAdSizeMapping the banner is displayed:

#### Before
```csharp
            case MaxAdSize.ScreenWidthHeight280:
                var pixels = Screen.width;
                var dpi = Screen.dpi;
                var dips = pixels / (dpi / 160.0f);
                return dips;
```
#### After
```csharp
            case MaxAdSize.ScreenWidthHeight280:
                // This is the value for LinearLayout.LayoutParams.MATCH_PARENT on Android; iOS will rehydrate to an
                // explicit size before sending the ad request.
                return -1;
```

**Comment by chauduyphanvu** [comment]
Thanks! I reproduced the issue now, and have let the rest of the team know. I'll update this thread once there's an update.
