### ISSUE TITLE
Mopub unity IOS plugin build Issue.

### ISSUE THREAD

**Issue by ahsanwqr** [mopub/mopub-unity-sdk#4]
I have been trying to build my Unity project in Xcode but In linking phase it gives me error. I have tried every possible solution available on Internet but there is no success.
Either I am building for architecture ( armv7 , arm64  ) or simple armv7 it gives the same linker error
(apple mach-o linker (id) error). Kindly help me out . I am stuck on this.
Please see the screen shot 
<img width="1016" alt="screen shot 2017-09-28 at 12 55 50 pm" src="https://user-images.githubusercontent.com/32355426/30955639-c02892b8-a44d-11e7-987b-957a80e7a703.png">

**Comment by aornelas** [comment]
Thanks for your report.

Please do the following:

1. Go to Project > Build Settings and set “Enable Modules” to YES and “Bitcode” to NO
1. Delete the “Native Code” folder in XCode and re-add it to the project
1. Go to Build Phases and delete any reference to Android files in Copy Bundle Resources
1. Build and run on a device

That should fix the problem, but feel free to reopen this issue otherwise.

Regards,
Andrés
