### ISSUE TITLE
Apple match-0 linker (id) error! 

### ISSUE THREAD

**Issue by il2stumovik** [mopub/mopub-unity-sdk#5]
I tried to import mopub package to the empty Unity project then export to Xcode. After build, I still got the issue (apple mach-o linker (id) error). Kindly help me out . I am stuck on this.

**Comment by aornelas** [comment]
Thanks for your report.

Please do the following:

1. Go to Project > Build Settings and set “Enable Modules” to YES and “Bitcode” to NO
1. Delete the “Native Code” folder in XCode and re-add it to the project
1. Go to Build Phases and delete any reference to Android files in Copy Bundle Resources
1. Build and run on a device

That should fix the problem, but feel free to reopen this issue otherwise.

Regards,
Andrés

**Comment by il2stumovik** [comment]
Hi, 

Thanks for your instruction. I followed your steps but still got the build issues as attached image 
<img width="1395" alt="screen shot 2017-10-10 at 3 18 32 pm" src="https://user-images.githubusercontent.com/13163368/31376268-8aad2c68-adce-11e7-9406-0974ac1e9fe5.png">

Here is the image when I completed yours 04 steps
<img width="1397" alt="screen shot 2017-10-10 at 3 17 34 pm" src="https://user-images.githubusercontent.com/13163368/31376297-a89a3518-adce-11e7-8e8e-11150229be49.png">

Please let me know if I do anything wrong here :(

Thank you!

**Comment by aornelas** [comment]
For anyone else struggling with this issue, please refer to this solution: https://github.com/mopub/mopub-unity-sdk/issues/6#issuecomment-342332694
