### ISSUE TITLE
 No callback when consent dialog closed without answering

### ISSUE THREAD

**Issue by sayiliromer** [mopub/mopub-unity-sdk#61]
It is possible to close consent dialog without answering and there is no callback for it. It is really hard to build a good flow without that. 

- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by chauduyphanvu1** [comment]
@sayiliromer, right now we don't have a callback for when the consent dialog is closed, but I've logged a feature request internally to get that supported. 

Vu Chau
MoPub SDK Team

**Comment by wacamoe** [comment]
enhancement request filed

**Comment by TJClifton90** [comment]
@wacamoe Was there a reason that this issue was closed? This issue still exists in v5.11.1 of the Unity MoPub SDK.

It is not really an enhancement as MoPubManager contains the event `OnConsentDialogDismissedEvent`. This event fires when closing a consent dialog on Android but does not on iOS so this is in fact a bug with unexpected behaviour. As @sayiliromer mentioned this bug means that we can't respond to that dialog closing which is resulting in different behaviour for us on iOS and Android. This is an important bug for us.

**Comment by TJClifton90** [comment]
So as an example of our current user flow, we attempt to show an ad after the user has been shown the consent dialog. At present this is impossible on iOS as the `OnConsentDialogDismissedEvent` does not get fired. The `OnConsentDialogShownEvent` event does fire, but it is inappropriate to show an ad at that stage as the Consent Dialog is still active. 

This event is crucial to our user flow and not an optional extra.

**Comment by chauduyphanvu** [comment]
@TJClifton90, thanks for letting us know! Could you confirm that:

1. The dismiss event fires on Android but not on iOS?
2. The behavior happens in the MoPub Unity SDK?

If 2 is not reproducible, could you send over a copy of your Unity project so we can investigate? Thanks!

Vu Chau
MoPub Team
