### ISSUE TITLE
Does Mopub unity support GDPR AND CCPA ? if yes which versions of SDK for each

### ISSUE THREAD

**Issue by shanukp** [mopub/mopub-unity-sdk#93]

**Comment by chauduyphanvu** [comment]
@shanukp,
Yes, MoPub does plan to be fully compliant with CCPA by 1/1.

MoPub already supports an on device method for users to opt-out of their data being used for advertising (see: https://www.mopub.com/legal/privacy/) and this will be leveraged to help publishers comply w/their obligations under CCPA. We will be making the appropriate changes on MoPub.com to direct any CA users to this page so that they can opt-out of their data from being sold.

Please note that this ensures CCPA compliance for MoPub. Partners (DSPs, publishers, networks and vendors) are still responsible for ensuring their own compliance.

Publishers on SDK version 5.1 and above have the ability to be more flexible in defining which users are subject to GDPR. This feature allows a publisher to extend the GDPR consent collection mechanism to users outside of the European Economic Area. 

A publisher that is using their own consent mechanism could use this feature to collect consent for CA users. We will process the data the same way as we do GDPR traffic (but this also means that it has to be an opt-in, meaning we will treat unknowns as explicit no consent). 

Vu Chau
MoPub Team
