### ISSUE TITLE
Admob under Mopub Mediation with auto initialize for GDPR consent

### ISSUE THREAD

**Issue by stefanivalinov** [mopub/mopub-unity-sdk#98]
Is it possible to use auto initialize on Start with MopubManager prefab with admob ad network for GDPR countries? If yes how can we change the NPA value for Admob while user accept the GDPR consent on auto initialize ?
We are using Mopub  5.10.0 release on unity.

**Comment by chauduyphanvu** [comment]
@stefanivalinov, from Unity and the MoPubManager Prefab, it is not possible to change the `npa` value while the game is in session, because the NPA is passed by default when MoPub initializes. You will need to wait until the next time your app initializes the MoPub SDK (naturally on the next app launch) to pass a new `npa` value.

If your app has logic to call underlying Android and iOS code in the adapters, you can call [`GooglePlayServicesAdapterConfiguration.setNpaBundle(String npaValue)`](https://github.com/mopub/mopub-android-mediation/blob/master/AdMob/src/main/java/com/mopub/mobileads/GooglePlayServicesAdapterConfiguration.java#L104-L110) (Android) and [`[GoogleAdMobAdapterConfiguration setNpaString:@"npaString"]`](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/GoogleAdMobAdapterConfiguration.m#L88-L91) (iOS) anytime during the game with a new `npa` value.

Vu Chau
MoPub Team
